spring:
  flyway:
    out-of-order: true
server:
  port: 8080
app:
  artist.query.limit: 100
---
spring:
  config.activate.on-profile: test
  datasource:
    generate-unique-name: false
    name: artists
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    locations: "classpath:db/pgsql/migrations"
app:
  artist.query.limit: 10
---
spring:
  config.activate.on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  flyway:
    locations: "classpath:db/pgsql/migrations"
